# Change baseurl before deploy
baseURL = "https://infyniteheap.github.io"
locale = "zh"
title = "InfyniteHeap's Personal Blog"

# Theme i18n support
# See the theme's i18n folder for available languages
# (e.g. zh, zh-hant-tw, zh-hant-hk, ja, ko, en, ...)
defaultContentLanguage = "zh"

# Set hasCJKLanguage to true if DefaultContentLanguage is a CJK language
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
[services.disqus]
shortname = "hugo-theme-stack"

[pagination]
pagerSize = 5
